INSERT INTO roles (name)
SELECT 'ROLE_ADMIN'
FROM roles
WHERE NOT EXISTS (SELECT * FROM roles WHERE name = 'ROLE_ADMIN');


INSERT INTO roles (name)
SELECT 'ROLE_USER'
FROM roles
WHERE NOT EXISTS (SELECT * FROM roles WHERE name = 'ROLE_USER');